# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14f0cd15d3a7aea68c814fd37195c4ec33f5c3e245db6f2895e11759ce48d6200d62259011fd719a90562c9ba62cc1dbbaecebad94e80799414851a8375ab76

test:
  secret_key_base: ecb4abb2a19bc2329ef246dbd924acccaaffd230c5c615456510dfe9576573af5d3b0c98e9f94cd246796e63bb990d9b2e3d00b1ad06bcc1e73a1955ae9685a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
